export const EMBEDDED_FLOW_RUNTIME_APP_PATH = "analysis_flow/app.js";
export const EMBEDDED_FLOW_RUNTIME_LOADER_PATH = "analysis_flow/runtime-loader.js";

export const EMBEDDED_FLOW_RUNTIME_SCRIPT_PATHS = [
  "analysis_flow/restricted-pii-projection.js",
  "analysis_flow/browser-bridge-mapper.js",
  "analysis_flow/canvas-shell-adapter.js",
  "analysis_flow/canvas-command-adapter.js",
  "analysis_flow/canvas-drag-controller.js",
  "analysis_flow/canvas-drill-controller.js",
  "analysis_flow/canvas-hit-viewport-controller.js",
  "analysis_flow/canvas-interaction-store.js",
  "analysis_flow/canvas-redraw-controller.js",
  "analysis_flow/flow-observability-adapter.js",
  "analysis_flow/flow-debug-diagnostics.js",
  "analysis_flow/flow-debug-surface.js",
  "analysis_flow/graph-mutation-store.js",
  "analysis_flow/graph-patch-adapter.js",
  "analysis_flow/graph-clipboard-model.js",
  "analysis_flow/graph-engine-primitives.js",
  "analysis_flow/graph-renderer-bootstrap.js",
  "analysis_flow/graph-renderer-orchestration.js",
  "analysis_flow/graph-renderer-init.js",
  "analysis_flow/graph-attribute-binding.js",
  "analysis_flow/graph-label-pipeline.js",
  "analysis_flow/graph-text-render-pass.js",
  "analysis_flow/graph-edge-worker-bootstrap.js",
  "analysis_flow/graph-edge-routing.js",
  "analysis_flow/graph-edge-offset-model.js",
  "analysis_flow/graph-text-atlas.js",
  "analysis_flow/graph-minimap-core.js",
  "analysis_flow/graph-data-model.js",
  "analysis_flow/graph-search-model.js",
  "analysis_flow/analysis-graph-data-model.js",
  "analysis_flow/graph-merge-model.js",
  "analysis_flow/graph-transaction-model.js",
  "analysis_flow/graph-edge-txn-query-model.js",
  "analysis_flow/graph-transaction-detail-render-model.js",
  "analysis_flow/graph-transaction-detail-row-model.js",
  "analysis_flow/graph-transaction-modal-controller.js",
  "analysis_flow/graph-edge-detail-render-model.js",
  "analysis_flow/graph-node-detail-render-model.js",
  "analysis_flow/graph-info-popover-controller.js",
  "analysis_flow/graph-drawer-controller.js",
  "analysis_flow/graph-detail-command-controller.js",
  "analysis_flow/graph-render-model.js",
  "analysis_flow/graph-projection-layout-model.js",
  "analysis_flow/graph-projection-layout-sync-model.js",
  "analysis_flow/layout-worker-contract.js",
  "analysis_flow/layout-meta-model.js",
  "analysis_flow/graph_engine.js",
  "analysis_flow/compact.js",
  "analysis_flow/network-rust-cluster-plan.js",
  "analysis_flow/network.js",
  "analysis_flow/hierarchy.js",
  "analysis_flow/flow.js",
  "analysis_flow/layout-runtime-adapter.js",
  "analysis_flow/layout-node-plan-client.js",
  "analysis_flow/layout-role-projection-client.js",
  "analysis_flow/layout-node-update-model.js",
  "analysis_flow/layout-worker-result-model.js",
  "analysis_flow/layout-graph-apply-model.js",
  "analysis_flow/layout-graph-apply-controller.js",
  "analysis_flow/layout-worker-lifecycle-controller.js",
  "analysis_flow/layout-worker-scheduler-controller.js",
  "analysis_flow/layout-prewarm-controller.js",
  "analysis_flow/layout-cluster-model.js",
  "analysis_flow/layout-plan-cache-apply-model.js",
  "analysis_flow/layout-plan-cache-model.js",
  "analysis_flow/layout-plan-cache-controller.js",
  "analysis_flow/layout-network-model.js",
  "analysis_flow/layout-network-presentation-model.js",
  "analysis_flow/minimap.js",
  "analysis_flow/graph-minimap-orchestration.js",
  "analysis_flow/overlay-adapter.js",
  "analysis_flow/flow-runtime-state.js",
  "analysis_flow/flow-layout-command-store.js",
  "analysis_flow/flow-shell-state-store.js",
  "analysis_flow/flow-session-store.js",
  "analysis_flow/flow-shell-sync-store.js",
  "analysis_flow/flow-graph-command-store.js",
  "analysis_flow/flow-selection-store.js",
  "analysis_flow/flow-view-sync-store.js",
  "analysis_flow/graph-render-plan-client.js",
  "analysis_flow/network-sector-placement-cache.js",
  "analysis_flow/network-sector-placement-client.js",
  "analysis_flow/flow-shell-facade.js",
  "analysis_flow/flow-shell-toolbar-commands.js",
  "analysis_flow/flow-shell-analysis-commands.js",
  "analysis_flow/flow-shell-canvas-commands.js",
  "analysis_flow/flow-shell-overlay-commands.js",
  EMBEDDED_FLOW_RUNTIME_APP_PATH,
] as const;

export function resolveEmbeddedFlowRuntimeScriptUrls(
  resolveRuntimeUrl: (relativePath: string) => string
): string[] {
  return EMBEDDED_FLOW_RUNTIME_SCRIPT_PATHS.map((scriptPath) => resolveRuntimeUrl(scriptPath));
}
