export type ThemeName = "light" | "dark";

export type ThemeTokens = Record<string, string>;

export const THEME_TOKENS: Record<ThemeName, ThemeTokens> = {
  light: {
    "color-bg": "#fcfcfc",
    "color-bg-elevated": "#ffffff",
    "color-bg-subtle": "#f3f3f3",
    "color-text": "#0d0d0d",
    "color-text-muted": "#5d5d5d",
    "color-border": "rgba(0, 0, 0, 0.08)",
    "color-accent": "#0d0d0d",
    "color-accent-strong": "#0d0d0d",
    "color-success": "#199f62",
    "color-warning": "#cd8a22",
    "color-danger": "#d94a4a",
    "shadow-card": "none",
    "shadow-elevated": "0 8px 24px rgba(0, 0, 0, 0.12)",
    "gradient-atmosphere": "none",
    "sidebar-surface": "#fcfcfc",
    "sidebar-subtle": "#f3f3f3",
    "sidebar-hover": "#ebebeb",
    "sidebar-icon": "#ebebeb",
    "sidebar-control-border": "rgba(0, 0, 0, 0.08)",
    "sidebar-active-start": "#0d0d0d",
    "sidebar-active-end": "#0d0d0d",
    "sidebar-active-shadow": "none",
    "sidebar-segment-surface": "#ffffff",
    "sidebar-segment-border": "rgba(0, 0, 0, 0.08)",
    "sidebar-segment-inactive": "#5d5d5d",
    "sidebar-segment-active-start": "#0d0d0d",
    "sidebar-segment-active-end": "#0d0d0d",
    "sidebar-segment-active-shadow": "none",
    "sidebar-nav-active-bg": "#ebebeb",
    "sidebar-nav-active-text": "#0d0d0d",
    "sidebar-icon-color": "#8f8f8f",
    "sidebar-icon-active-color": "#0d0d0d",
    "sidebar-badge-accent": "#ebebeb",
    "sidebar-badge-warn": "#f0e6d8",
    "sidebar-badge-muted": "#f3f3f3",
    "sidebar-separator": "rgba(0, 0, 0, 0.08)",
    "sidebar-soft-shadow": "none",
    "sidebar-soft-inset": "none"
  },
  dark: {
    "color-bg": "#181818",
    "color-bg-elevated": "#212121",
    "color-bg-subtle": "#2f2f2f",
    "color-text": "#ececec",
    "color-text-muted": "#b4b4b4",
    "color-border": "rgba(255, 255, 255, 0.1)",
    "color-accent": "#ececec",
    "color-accent-strong": "#ececec",
    "color-success": "#48c981",
    "color-warning": "#dfb059",
    "color-danger": "#ff7a87",
    "shadow-card": "none",
    "shadow-elevated": "0 8px 24px rgba(0, 0, 0, 0.32)",
    "gradient-atmosphere": "none",
    "sidebar-surface": "#212121",
    "sidebar-subtle": "#2f2f2f",
    "sidebar-hover": "#383838",
    "sidebar-icon": "#383838",
    "sidebar-control-border": "rgba(255, 255, 255, 0.1)",
    "sidebar-active-start": "#ececec",
    "sidebar-active-end": "#ececec",
    "sidebar-active-shadow": "none",
    "sidebar-segment-surface": "#212121",
    "sidebar-segment-border": "rgba(255, 255, 255, 0.1)",
    "sidebar-segment-inactive": "#b4b4b4",
    "sidebar-segment-active-start": "#ececec",
    "sidebar-segment-active-end": "#ececec",
    "sidebar-segment-active-shadow": "none",
    "sidebar-nav-active-bg": "#383838",
    "sidebar-nav-active-text": "#ececec",
    "sidebar-icon-color": "#b4b4b4",
    "sidebar-icon-active-color": "#ececec",
    "sidebar-badge-accent": "#383838",
    "sidebar-badge-warn": "#665534",
    "sidebar-badge-muted": "#2f2f2f",
    "sidebar-separator": "rgba(255, 255, 255, 0.1)",
    "sidebar-soft-shadow": "none",
    "sidebar-soft-inset": "none"
  }
};

export const RADIUS_TOKENS: Record<string, string> = {
  "radius-sm": "8px",
  "radius-md": "14px",
  "radius-lg": "20px",
  "radius-xl": "30px"
};

export const SPACE_TOKENS: Record<string, string> = {
  "space-1": "4px",
  "space-2": "8px",
  "space-3": "12px",
  "space-4": "16px",
  "space-5": "24px",
  "space-6": "32px"
};
