export const MACOS_TRAFFIC_LIGHT_POSITION = {
  x: 16,
  y: 16
} as const

export const MACOS_TRAFFIC_LIGHT_CLUSTER_WIDTH = 66
export const MACOS_TRAFFIC_LIGHT_GAP = 18

export const MACOS_TITLEBAR_SAFE_LEFT =
  MACOS_TRAFFIC_LIGHT_POSITION.x + MACOS_TRAFFIC_LIGHT_CLUSTER_WIDTH + MACOS_TRAFFIC_LIGHT_GAP
