import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { tmpdir } from 'node:os'
import { fileURLToPath } from 'node:url'
import { dirname, join, resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..')
const require = createRequire(import.meta.url)
const windowsPayloadContract = require('../../scripts/windows-payload-contract.cjs')

function readRepoFile(relativePath: string): string {
  return readFileSync(join(repoRoot, relativePath), 'utf8')
}

describe('standard Windows bootstrapper migration', () => {
  it('keeps the WinForms/WebView2 installer wrapper and native traffic controls', () => {
    const source = readRepoFile('installer/winforms-bootstrapper/AnalytixWinFormsBootstrapper.cs')

    expect(source).toContain('InstallerTrafficControlHitTargets')
    expect(source).toContain('FormBorderStyle = FormBorderStyle.None')
    expect(source).toContain('data-analytix-installer-prepaint')
    expect(source).toContain('analytix-installer-surface')
    expect(source).toContain('surfaceReady')
    expect(source).toContain('window.analytixInstaller = installerBridge')
    expect(source).toContain("platform: 'win32'")
    expect(source).toContain('private const string AppExeName = "analytix.exe"')
    expect(source).toContain('private const string ProductDisplayName = "Analytix灵鉴"')
    expect(source).toContain('private const string LegacyProductDisplayName = "Analytix"')
    expect(source).toContain('private const string UninstallerDirectoryName = "AnalytixUninstaller"')
    expect(source).toContain('private const string UninstallRegistryPath = @"Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Analytix"')
    expect(source).toContain('public const string CurrentVersionText = "1.0.6"')
    expect(source).toContain('private static readonly Version CurrentPackageVersion = new Version(1, 0, 6, 0)')
    expect(source).toContain("version: 'winforms-webview2-bootstrapper-1.0.6'")
    expect(source).toContain('ProductDisplayName + ".lnk"')
    expect(source).toContain('Environment.SpecialFolder.CommonDesktopDirectory')
    expect(source).toContain('Environment.SpecialFolder.CommonPrograms')
    expect(source).toContain('Registry.LocalMachine.CreateSubKey(UninstallRegistryPath)')
    expect(source).toContain('DeleteLegacyShortcuts')
    expect(source).toContain('"Analytix.lnk"')
    expect(source).toContain('resources\\app.asar.unpacked\\packages\\runtime\\node_modules\\analytix-computer-use\\dist\\windows\\amd64\\analytix-computer-use.exe')
    expect(source).toContain('ResolveLegacyExternalUninstallerPath')
    expect(source).toContain('public bool ElectronUpdaterSilent { get; private set; }')
    expect(source).toContain('return InstallSilent || UninstallSilent || ElectronUpdaterSilent')
    expect(source).toContain('EqualsArg(arg, "--updated")')
    expect(source).toContain('EqualsArg(arg, "--force-run")')
    expect(source).toContain('EqualsArg(arg, "--squirrel-updated")')
    expect(source).toContain('result.InstallSilent = true;')
    expect(source).toContain('result.LaunchAfterInstall = true;')
    expect(source).toContain('result.InstallPath = InstallerOperations.ResolveInstalledPath();')
    expect(source).toContain('private const string WebView2RuntimeInstallerResourceName = "WebView2RuntimeInstaller"')
    expect(source).toContain('EnsureEvergreenRuntimeAvailable();')
    expect(source).toContain('MicrosoftEdgeWebView2RuntimeInstallerX64.exe')
    expect(source).toContain('CoreWebView2Environment.GetAvailableBrowserVersionString()')
    expect(source).toContain('RunWebView2RuntimeInstaller(installerPath)')
    expect(source).toContain('User data intentionally stays on disk')
    const uninstallBody = source.match(/public static void Uninstall\(string installPath\)\r?\n\s+\{([\s\S]*?)\r?\n\s+\}\r?\n\r?\n\s+private static string ToPowerShellSingleQuotedString/)
    expect(uninstallBody?.[1]).not.toContain('DeleteAnalytixUserData')
    expect(source).toMatch(/result\.InstallSilent = true;\r?\n\s+result\.LaunchAfterInstall = false;/)
    expect(source).not.toContain('window.analytixDesktop =')
  })

  it('fills the WebView2 installer window with the React installer surface', () => {
    const source = readRepoFile('installer/winforms-bootstrapper/AnalytixWinFormsBootstrapper.cs')
    const installerTsx = readRepoFile('src/renderer/src/installer/WindowsPackageInstaller.tsx')
    const installerCss = readRepoFile('src/renderer/src/installer/windows-package-installer.css')

    expect(source).toContain('Size = new Size(1360, 760)')
    expect(source).toContain('Dock = DockStyle.Fill')
    expect(installerTsx).toContain("document.body.classList.add('analytix-installer-surface')")
    expect(installerTsx).toContain('window.__analytixReleaseInstallerPrepaint?.()')
    expect(installerTsx).toContain('className="win-package-installer__logo"')
    expect(installerCss).toContain('body.analytix-installer-surface')
    expect(installerCss).toContain('.win-package-installer__logo .ax-loading-logo__overlay')
    expect(installerCss).toContain('ax-loading-logo-shimmer 1.9s cubic-bezier(0.4, 0, 0.2, 1) infinite !important')
    expect(installerCss).toContain('zoom: 1;')
    expect(installerCss).toContain('align-items: stretch;')
    expect(installerCss).toContain('justify-content: stretch;')
    expect(installerCss).toContain('padding: 0;')
    expect(installerCss).toContain('width: 100%;')
    expect(installerCss).toContain('min-height: 100vh;')
    expect(installerCss).toContain('border: 0;')
    expect(installerCss).toContain('border-radius: 0;')
    expect(installerCss).toContain('box-shadow: none;')
    expect(installerCss).not.toContain('width: min(760px')
  })

  it('wraps the standard Windows NSIS payload into the final bootstrapper artifact', () => {
    const packageJson = JSON.parse(readRepoFile('package.json')) as { scripts: Record<string, string> }
    const postpackage = readRepoFile('scripts/postpackage-standard-win-bootstrapper.cjs')
    const buildScript = readRepoFile('scripts/build-standard-win-bootstrapper.ps1')
    const releasePowerShell = readRepoFile('scripts/release-win.ps1')
    const releaseBash = readRepoFile('scripts/release-win.sh')
    const publishR2 = readRepoFile('scripts/publish-r2.mjs')
    const releaseEnvExample = readRepoFile('scripts/release.local.env.example')
    const archivePowerShell = readRepoFile('scripts/archive-standard-win-release.ps1')
    const packageAudit = readRepoFile('scripts/audit-windows-package.cjs')

    expect(packageJson.scripts['dist:win:standard']).toBe('npm run dist:win:official')
    expect(packageJson.scripts['dist:win:official']).toContain('scripts/postpackage-standard-win-bootstrapper.cjs')
    expect(postpackage).toContain("ANALYTIX_STANDARD_WIN_PAYLOAD_ONLY")
    expect(postpackage).toContain("process.platform !== 'win32'")
    expect(buildScript).toContain('dist-standard-win')
    expect(buildScript).toContain('win-unpacked')
    expect(buildScript).toContain('out\\renderer')
    expect(buildScript).toContain('AnalytixPayloadZip')
    expect(buildScript).toContain('AnalytixInstallerUiZip')
    expect(buildScript).toContain('function Remove-BuildMetadataFiles')
    expect(buildScript).toContain('.DS_Store')
    expect(buildScript).toContain('._')
    expect(buildScript).toContain('function New-ZipFromDirectory')
    expect(buildScript).toContain('function New-SevenZipFromDirectory')
    expect(buildScript).toContain('function Resolve-SevenZipPath')
    expect(buildScript).toContain('AnalytixPayload.7z')
    expect(buildScript).toContain('PayloadExtractorExe')
    expect(buildScript).toContain('AnalytixPayloadManifest')
    expect(buildScript).toContain('windows-payload-contract.cjs')
    expect(buildScript).toContain('Prebuilt payload archives are forbidden')
    expect(buildScript).toContain('$payloadSourceDir')
    expect(buildScript).toContain('$payloadVerificationDir')
    expect(buildScript).toContain('Sign-BootstrapperIfConfigured -Path $payloadExtractor')
    expect(buildScript).toContain('ANALYTIX_WINDOWS_EXPECTED_SIGNER_SHA1')
    expect(buildScript).toContain('-m0=LZMA2')
    expect(buildScript).toContain('-mx=9')
    expect(buildScript).toContain('-bb0')
    expect(buildScript).not.toContain('-bb1')
    expect(buildScript).toContain('$extendedSourceDirectory = ConvertTo-ExtendedWindowsPath $SourceDirectory')
    expect(buildScript).toContain('function Save-DownloadFile')
    expect(buildScript).toContain('https://api.nuget.org/v3-flatcontainer/microsoft.web.webview2/')
    expect(buildScript).toContain('Downloaded file is empty')
    expect(buildScript).toContain('ANALYTIX_WEBVIEW2_RUNTIME_INSTALLER_SOURCE')
    expect(buildScript).toContain('ANALYTIX_WEBVIEW2_RUNTIME_INSTALLER_URL')
    expect(buildScript).toContain('ANALYTIX_WEBVIEW2_RUNTIME_INSTALLER_SHA256')
    expect(buildScript).toContain('function Resolve-WebView2RuntimeInstaller')
    expect(buildScript).toContain('MicrosoftEdgeWebView2RuntimeInstallerX64.exe')
    expect(buildScript).toContain('analytix-webview2-runtime-manifest.json')
    expect(buildScript).toContain('webview2RuntimeSha256')
    expect(buildScript).toContain('/resource:$webView2RuntimeInstaller,WebView2RuntimeInstaller')
    expect(buildScript).toContain('function Resolve-AppBuilderPath')
    expect(buildScript).toContain('app-builder-bin\\win\\x64\\app-builder.exe')
    expect(buildScript).toContain('npm config get cache')
    expect(buildScript).toContain('Join-Path $cacheRoot "_npx"')
    expect(buildScript).toContain('function Sign-BootstrapperIfConfigured')
    expect(buildScript).toContain('[AllowNull()]')
    expect(buildScript).toContain('ANALYTIX_WIN_SIGNING_CERT_PATH')
    expect(buildScript).toContain('WIN_CSC_LINK')
    expect(buildScript).toContain('CSC_LINK')
    expect(buildScript).toContain('signing=NotSigned')
    expect(buildScript).toContain('analytix-standard-$version-x64.exe')
    expect(buildScript).toContain('isAdminRightsRequired: true')
    expect(packageAudit).toContain('blocked-before-resource-extraction')
    expect(packageAudit).toContain('embedded extractor is not trusted')
    expect(releasePowerShell).toContain("Get-Command 'npm.cmd'")
    expect(releasePowerShell).toContain('& $NpmCommand run build')
    expect(releasePowerShell).toContain("'CARGO_TARGET_DIR'")
    expect(releasePowerShell).not.toMatch(/^\s*\$env:CARGO_TARGET_DIR\s*=/m)
    expect(releasePowerShell).toContain('ANALYTIX_RELEASE_CACHE_DISABLE')
    expect(releasePowerShell).not.toContain('npm run dist:win:official')
    expect(releasePowerShell).toContain("publish-r2.mjs') verify")
    expect(releasePowerShell).toContain('--authority $ReleaseAuthority')
    expect(releasePowerShell).toContain('--public-key $ReleaseAuthorityPublicKey')
    expect(releasePowerShell).toContain('-LocalNonPublishable')
    expect(releasePowerShell).toContain('--publish never --win --dir --x64')
    expect(releasePowerShell).toContain('dist-standard-win')
    expect(releasePowerShell).toContain('analytix-standard-*-x64.exe')
    expect(releasePowerShell).toContain('--dist $DistDir')
    expect(releasePowerShell).toContain('archive-standard-win-release.ps1')
    expect(releasePowerShell).toContain('-AuditPath $AuditPath')
    expect(releasePowerShell).toContain('-DesktopLatest')
    expect(archivePowerShell).toContain('ANALYTIX_WINDOWS_RELEASE_ARCHIVE_ROOT')
    expect(archivePowerShell).toContain("Analytix-Releases\\win")
    expect(archivePowerShell).toContain("analytix-standard-$CleanVersion-x64.exe")
    expect(archivePowerShell).toContain('SHA256SUMS.txt')
    expect(archivePowerShell).toContain('DesktopDirectory')
    expect(releaseBash).not.toContain('npm run dist:win:official')
    expect(releaseBash).toContain('publish-r2.mjs" verify')
    expect(releaseBash).toContain('--authority "${RELEASE_AUTHORITY_PATH}"')
    expect(releaseBash).toContain('--public-key "${RELEASE_AUTHORITY_PUBLIC_KEY}"')
    expect(releaseBash).toContain('--local-nonpublishable')
    expect(releaseBash).toContain('--publish never --win --dir --x64')
    expect(releaseBash).toContain('dist-standard-win/analytix-standard-*-x64.exe')
    expect(releaseBash).toContain('--dist "${ROOT}/dist-standard-win"')
    expect(publishR2).toContain("assetPattern: /^analytix-standard-.+-x64\\.exe(\\.blockmap)?$/")
    expect(publishR2).toContain("distDir: 'dist-standard-win'")
    expect(releaseEnvExample).toContain('ANALYTIX_RELEASE_PREFIX=analytix')
    expect(releaseEnvExample).toContain('ANALYTIX_WINDOWS_RELEASE_CACHE=')
    expect(releaseEnvExample).toContain('ANALYTIX_WINDOWS_RELEASE_ARCHIVE_ROOT=')
    expect(releaseEnvExample).toContain('ANALYTIX_WINDOWS_EXPECTED_SIGNER_SHA1=')
    expect(releaseEnvExample).toContain('ANALYTIX_STANDARD_WIN_UPDATE_FEED_URL=')
    expect(releaseEnvExample).not.toContain('R2_RELEASE_PREFIX=')
  })

  it('prunes build-only payload files before embedding the Windows payload', () => {
    const buildScript = readRepoFile('scripts/build-standard-win-bootstrapper.ps1')
    const bootstrapperSource = readRepoFile('installer/winforms-bootstrapper/AnalytixWinFormsBootstrapper.cs')

    expect(buildScript).toContain('function Remove-BuildOnlyPayloadFiles')
    expect(buildScript).toContain('src\\__image_snapshots__')
    expect(buildScript).toContain('src\\__snapshots__')
    expect(buildScript).toContain('ConvertTo-ExtendedWindowsPath')
    expect(buildScript).toContain('(Join-Path $Root "resources\\app.asar.unpacked\\packages\\runtime\\node_modules\\@jimp"),')
    expect(buildScript).toContain('(Join-Path $Root "resources\\app.asar.unpacked\\node_modules\\@jimp")')
    const extractorSignIndex = buildScript.indexOf('Sign-BootstrapperIfConfigured -Path $payloadExtractor')
    const pruneIndex = buildScript.indexOf('Remove-BuildOnlyPayloadFiles $payloadSourceDir')
    const archiveIndex = buildScript.indexOf('New-SevenZipFromDirectory $payloadSourceDir $payloadArchive $payloadExtractor')
    const signIndex = buildScript.indexOf('Sign-BootstrapperIfConfigured $outputPath $workDir')
    const blockmapIndex = buildScript.indexOf('& $appBuilder "blockmap" "--input" $outputPath')
    expect(pruneIndex).toBeGreaterThan(-1)
    expect(archiveIndex).toBeGreaterThan(-1)
    expect(extractorSignIndex).toBeGreaterThan(-1)
    expect(signIndex).toBeGreaterThan(-1)
    expect(blockmapIndex).toBeGreaterThan(-1)
    expect(pruneIndex).toBeLessThan(archiveIndex)
    expect(extractorSignIndex).toBeLessThan(archiveIndex)
    expect(signIndex).toBeLessThan(blockmapIndex)
    expect(bootstrapperSource).toContain('private const string PayloadResourceName = "AnalytixPayloadArchive"')
    expect(bootstrapperSource).toContain('ExtractManifestResourceToFile("PayloadExtractorExe"')
    expect(bootstrapperSource).toContain('ExtractManifestResourceToFile("AnalytixPayloadManifest"')
    expect(bootstrapperSource).toContain('VerifyPayloadBlob(archivePath')
    expect(bootstrapperSource).toContain('VerifyExtractedPayload(targetDir, manifest)')
    expect(bootstrapperSource).toContain('VerifyTrustedBootstrapperExecutables(extractorPath)')
    expect(bootstrapperSource).toContain('"$tab=[char]9;"')
    expect(bootstrapperSource).toContain('+$tab+$thumb+$tab+$timestamp')
    expect(bootstrapperSource).toContain("entryPath = entryPath.Replace('\\\\', '/');")
    expect(bootstrapperSource).toContain('CollectPayloadFilesNoFollow(targetDir)')
    expect(bootstrapperSource).toContain('ValidateInstallTarget(installPath, false)')
    expect(bootstrapperSource).toContain('Directory.Move(stagingDir, targetDir)')
    expect(bootstrapperSource).toContain('Directory.Move(backupDir, targetDir)')
    expect(bootstrapperSource).toContain('@"resources\\runtime-go\\bin\\runtime-server.exe"')
    expect(bootstrapperSource).toContain('ValidateSevenZipPayloadEntries')
    expect(bootstrapperSource).toContain('ValidateArchiveEntryPath')
    expect(bootstrapperSource).toContain('RunProcessAndCapture')
  })

  it('binds the final bootstrapper archive and extracted tree to a canonical payload manifest', () => {
    const temporaryRoot = mkdtempSync(join(tmpdir(), 'analytix-windows-payload-'))
    try {
      const payloadRoot = join(temporaryRoot, 'payload')
      const archive = join(temporaryRoot, 'AnalytixPayload.7z')
      const extractor = join(temporaryRoot, '7za.exe')
      const manifestPath = join(temporaryRoot, 'AnalytixPayloadManifest.json')
      mkdirSync(join(payloadRoot, 'resources', 'runtime-go', 'bin'), { recursive: true })
      writeFileSync(join(payloadRoot, 'analytix.exe'), 'app')
      writeFileSync(join(payloadRoot, 'resources', 'runtime-go', 'bin', 'runtime-server.exe'), 'runtime')
      writeFileSync(archive, 'archive')
      writeFileSync(extractor, 'extractor')
      const manifest = windowsPayloadContract.createPayloadManifest({
        root: payloadRoot,
        archive,
        extractor
      })
      writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, 'utf8')
      expect(windowsPayloadContract.verifyPayloadManifest({
        manifest: manifestPath,
        root: payloadRoot,
        archive,
        extractor
      })).toEqual(manifest)

      writeFileSync(join(payloadRoot, 'analytix.exe'), 'tampered')
      expect(() => windowsPayloadContract.verifyPayloadManifest({
        manifest: manifestPath,
        root: payloadRoot,
        archive,
        extractor
      })).toThrow(/tree does not match/)
      expect(() => windowsPayloadContract.validatePortablePayloadPath('resources/\uE000.txt')).toThrow(/portable ASCII/)
      expect(() => windowsPayloadContract.validatePortablePayloadPath('resources/CON.txt')).toThrow(/not portable/)
      expect(() => windowsPayloadContract.validatePortablePayloadPath('resources/name./file')).toThrow(/not portable/)
      expect(() => windowsPayloadContract.validatePortablePayloadPath('resources/file:stream')).toThrow(/not portable/)
    } finally {
      rmSync(temporaryRoot, { recursive: true, force: true })
    }
  })
})
