package documentgeneration

import (
	"context"
	"crypto/sha256"
	"errors"
	"testing"
	"time"

	domaincheckpoint "analytix.local/runtime-go/internal/domain/checkpointauthority"
	domaincheckpointref "analytix.local/runtime-go/internal/domain/checkpointref"
	identitydomain "analytix.local/runtime-go/internal/domain/identity"
	domainsecurity "analytix.local/runtime-go/internal/domain/security"
	checkpointfileport "analytix.local/runtime-go/internal/ports/checkpointfile"
	codecport "analytix.local/runtime-go/internal/ports/documentgeneration"
	securitytest "analytix.local/runtime-go/internal/testsupport/securitycontext"
)

type artifactTestIdentity struct {
	principal identitydomain.PrincipalV1
	invalid   bool
}

func (i *artifactTestIdentity) ResolveCurrent(context.Context) (identitydomain.PrincipalV1, error) {
	return i.principal, nil
}

func (i *artifactTestIdentity) ValidateCurrent(_ context.Context, principal identitydomain.PrincipalV1) error {
	if i.invalid || principal != i.principal {
		return errors.New("synthetic identity expired")
	}
	return nil
}

type artifactTestInventory struct {
	groups []domaincheckpoint.OperationGroupStateV2
}

func (i *artifactTestInventory) OperationGroups(context.Context) ([]domaincheckpoint.OperationGroupStateV2, error) {
	return i.groups, nil
}

type artifactTestFiles struct {
	inspect func(context.Context, string, checkpointfileport.PathAuthority, string, string) (codecport.ResolvedArtifact, error)
	calls   int
}

func (f *artifactTestFiles) InspectGenerated(ctx context.Context, workspace string, authority checkpointfileport.PathAuthority, kind, hash string) (codecport.ResolvedArtifact, error) {
	f.calls++
	return f.inspect(ctx, workspace, authority, kind, hash)
}

type artifactTestFixture struct {
	resolver    Resolver
	identity    *artifactTestIdentity
	inventory   *artifactTestInventory
	files       *artifactTestFiles
	accessCalls int
	result      codecport.ResolvedArtifact
}

func newArtifactTestFixture(t *testing.T) *artifactTestFixture {
	t.Helper()
	principal, err := identitydomain.NewPrincipalV1(domainsecurity.SHA256Hex([]byte("synthetic installation")), "local", "local")
	if err != nil {
		t.Fatal(err)
	}
	now := time.Unix(1_700_000_000, 0).UTC()
	securityContext, err := securitytest.GeneralExecutionContextV2(domainsecurity.TurnSecurityContextInput{
		ThreadID: "thr-artifact", TurnID: "turn-creation", WorkspaceRealPath: "/synthetic/workspace",
		TenantID: principal.TenantID, UserID: principal.UserID, ContextEpoch: 1, IssuedAt: now,
	})
	if err != nil {
		t.Fatal(err)
	}
	arguments := []byte(`{"path":"report.docx","kind":"docx","markdown":"Synthetic report"}`)
	entropy := sha256.Sum256([]byte("synthetic artifact tool call"))
	callID, err := domainsecurity.NewHostToolCallIDV1(entropy[:])
	if err != nil {
		t.Fatal(err)
	}
	grant := domainsecurity.NewExecutionGrant(domainsecurity.ExecutionGrantInput{
		Context: securityContext, Provider: "synthetic-provider", ServerIdentity: "host:builtin",
		ToolName: "generate_office_document", ToolCallID: callID,
		ArgsHash: domainsecurity.CanonicalJSONHash(arguments), SchemaHash: domainsecurity.SHA256Hex([]byte("schema")),
		ScopeHash: domainsecurity.SHA256Hex([]byte(`["generate_office_document"]`)), ApprovalState: "approved",
		IssuedAt: now, ExpiresAt: now.Add(time.Minute),
	})
	rootIdentity := "synthetic:workspace:1"
	path := domaincheckpoint.OperationPathInputV2{
		ArgumentKey: "path", RequestedPath: "report.docx", RelativePath: "report.docx", Role: "target",
		PathAuthoritySchemaVersion: 1, AuthorityKind: "workspace", AuthorityRoot: securityContext.WorkspaceRealPath,
		AuthorityRootIdentity: rootIdentity,
		AuthorityRootHash:     domainsecurity.SHA256Hex([]byte(securityContext.WorkspaceRealPath + "\x00" + rootIdentity)),
		ExpectedAfterExisted:  true, ExpectedAfterHash: domainsecurity.SHA256Hex([]byte("synthetic generated bytes")),
	}
	intent, err := domaincheckpoint.NewOperationGroupIntentV2(domaincheckpoint.OperationGroupIntentInputV2{
		SecurityContext: securityContext, ExecutionGrant: grant,
		CheckpointID: domaincheckpointref.RuntimeID("workspace-artifact"), SourceWorkspaceCheckpointID: "workspace-artifact",
		GenerationPrincipalDigest: principal.PrincipalDigest, OperationOrdinal: 1, ToolName: "generate_office_document",
		ArgumentsJSON: arguments, Paths: []domaincheckpoint.OperationPathInputV2{path}, CreatedAt: now.Add(time.Second),
	})
	if err != nil {
		t.Fatal(err)
	}
	terminal, err := domaincheckpoint.NewOperationGroupTerminalV2(domaincheckpoint.OperationGroupTerminalInputV2{
		Intent: intent, Status: "completed", ReasonCode: "mutation_completed", SettledAt: now.Add(2 * time.Second),
		ObservedPaths: []domaincheckpoint.ObservedOperationPathV2{{
			PathAuthoritySchemaVersion: path.PathAuthoritySchemaVersion, AuthorityKind: path.AuthorityKind,
			AuthorityRootHash: path.AuthorityRootHash, RelativePath: path.RelativePath,
			ObservationStatus: "exact", Existed: true, Hash: path.ExpectedAfterHash,
		}},
	})
	if err != nil {
		t.Fatal(err)
	}
	f := &artifactTestFixture{
		identity:  &artifactTestIdentity{principal: principal},
		inventory: &artifactTestInventory{groups: []domaincheckpoint.OperationGroupStateV2{{Intent: intent, Terminal: &terminal}}},
		result:    codecport.ResolvedArtifact{Path: "/synthetic/workspace/report.docx", Revision: path.ExpectedAfterHash, ByteSize: 1234},
	}
	f.files = &artifactTestFiles{inspect: func(_ context.Context, workspace string, authority checkpointfileport.PathAuthority, kind, hash string) (codecport.ResolvedArtifact, error) {
		want := checkpointfileport.PathAuthority{SchemaVersion: 1, Kind: "workspace", Root: path.AuthorityRoot,
			RootIdentity: path.AuthorityRootIdentity, RootHash: path.AuthorityRootHash, RelativePath: "report.docx"}
		if workspace != securityContext.WorkspaceRealPath || authority != want || kind != "docx" || hash != path.ExpectedAfterHash {
			t.Fatal("file inspection did not receive the exact private creation authority")
		}
		return f.result, nil
	}}
	f.resolver = Resolver{Identity: f.identity, Inventory: f.inventory, Files: f.files,
		ValidateAccess: func(_ context.Context, got identitydomain.PrincipalV1, threadID, workspace string) error {
			f.accessCalls++
			if got != principal || threadID != "thr-artifact" || workspace != securityContext.WorkspaceRealPath {
				t.Fatal("access validation did not receive the current principal and original thread/workspace")
			}
			return nil
		},
	}
	return f
}

func TestArtifactResolverRecoversCreationAndPreservesCurrentRevision(t *testing.T) {
	for _, changed := range []bool{false, true} {
		t.Run(map[bool]string{false: "original", true: "subsequently-edited"}[changed], func(t *testing.T) {
			f := newArtifactTestFixture(t)
			if changed {
				f.result.Changed = true
				f.result.Revision = domainsecurity.SHA256Hex([]byte("synthetic edited bytes"))
			}
			id := f.inventory.groups[0].Intent.OperationGroupID
			got, err := f.resolver.Resolve(context.Background(), "thr-artifact", id)
			want := Resolved{ArtifactID: id, ThreadID: "thr-artifact", ResolvedArtifact: f.result, Workspace: "/synthetic/workspace", Kind: "docx"}
			if err != nil || got != want || f.files.calls != 1 || f.accessCalls != 2 {
				t.Fatalf("creation recovery failed: result=%+v error=%v inspections=%d access=%d", got, err, f.files.calls, f.accessCalls)
			}
		})
	}
}

func TestArtifactResolverRejectsUnauthorizedInventoryBeforeFileRead(t *testing.T) {
	for _, name := range []string{"old-principal", "wrong-thread", "duplicate-id", "unfinished", "no-effect", "workspace-denied"} {
		t.Run(name, func(t *testing.T) {
			f := newArtifactTestFixture(t)
			threadID := "thr-artifact"
			id := f.inventory.groups[0].Intent.OperationGroupID
			switch name {
			case "old-principal":
				// Both identities deliberately keep local/local; installation binding must distinguish them.
				principal, err := identitydomain.NewPrincipalV1(domainsecurity.SHA256Hex([]byte("replacement installation")), "local", "local")
				if err != nil {
					t.Fatal(err)
				}
				f.identity.principal = principal
			case "wrong-thread":
				threadID = "thr-other"
			case "duplicate-id":
				f.inventory.groups = append(f.inventory.groups, f.inventory.groups[0])
			case "unfinished":
				f.inventory.groups[0].Terminal = nil
			case "no-effect":
				group := &f.inventory.groups[0]
				observed := group.Terminal.ObservedPaths[0]
				observed.Existed, observed.Hash = false, ""
				terminal, err := domaincheckpoint.NewOperationGroupTerminalV2(domaincheckpoint.OperationGroupTerminalInputV2{
					Intent: group.Intent, Status: "no_effect", ReasonCode: "mutation_failed_before_effect",
					ObservedPaths: []domaincheckpoint.ObservedOperationPathV2{observed}, SettledAt: time.Unix(1_700_000_003, 0).UTC(),
				})
				if err != nil {
					t.Fatal(err)
				}
				group.Terminal = &terminal
			case "workspace-denied":
				f.resolver.ValidateAccess = func(context.Context, identitydomain.PrincipalV1, string, string) error {
					return errors.New("synthetic current workspace was reassigned")
				}
			}
			got, err := f.resolver.Resolve(context.Background(), threadID, id)
			if !errors.Is(err, ErrArtifactUnavailable) || got != (Resolved{}) || f.files.calls != 0 {
				t.Fatalf("unauthorized artifact was inspected or returned: result=%+v error=%v inspections=%d", got, err, f.files.calls)
			}
		})
	}
}

func TestArtifactResolverWithholdsPathWhenAuthorityExpiresDuringRead(t *testing.T) {
	for _, name := range []string{"principal", "workspace"} {
		t.Run(name, func(t *testing.T) {
			f := newArtifactTestFixture(t)
			if name == "workspace" {
				validateAccess := f.resolver.ValidateAccess
				f.resolver.ValidateAccess = func(ctx context.Context, principal identitydomain.PrincipalV1, threadID, workspace string) error {
					if f.files.calls > 0 {
						return errors.New("synthetic access revoked during read")
					}
					return validateAccess(ctx, principal, threadID, workspace)
				}
			}
			inspect := f.files.inspect
			f.files.inspect = func(ctx context.Context, workspace string, authority checkpointfileport.PathAuthority, kind, hash string) (codecport.ResolvedArtifact, error) {
				file, err := inspect(ctx, workspace, authority, kind, hash)
				if name == "principal" {
					f.identity.invalid = true
				}
				return file, err
			}
			got, err := f.resolver.Resolve(context.Background(), "thr-artifact", f.inventory.groups[0].Intent.OperationGroupID)
			if !errors.Is(err, ErrArtifactUnavailable) || got != (Resolved{}) || f.files.calls != 1 {
				t.Fatalf("revoked authority disclosed an artifact: result=%+v error=%v inspections=%d", got, err, f.files.calls)
			}
		})
	}
}
